### PR TITLE
12 factor refactor to fix #25

### LINKED ISSUE #25: Discussion: best practice Axios setup for production builds
As per vue-cli [docs](https://github.com/vuejs/vue-cli/blob/dev/docs/env.md#environment-variables-and-modes), environment-specific variables are configured separately from code – a la the "twelve-factor app" [methodology](https://12factor.net/config) – in `.env` files. [Only environment variables that start with `VUE_APP_` will be statically embedded into the client bundle](https://github.com/vuejs/vue-cli/blob/dev/docs/env.md#using-env-variables-in-client-side-code). So for a production build, you'd presumably have something like:

```
# .env.production (or .env.production.local if this file is to contain secrets)
VUE_APP_API_BASE_URL=https://api.example.com
```

And in code use a pattern similar to the following:

```js
// src/utils/http.js
import axios from 'axios';

const axiosInstance = axios.create({
  baseURL: process.env.VUE_APP_API_BASE_URL,
});

export default axiosInstance;
```

```js
// src/state/modules/auth.js (for example)
import http from '@utils/http';
...
const res = await http.post('/session');
...
```

However, this doesn't seem to play well with this project's use of Axios in tests: the Jest-backed mock, `test/unit/__mocks__/axios.js`, will be used when an equivalently named module is imported, i.e. `import axios from 'axios'`. But we're obviously not importing the node module directly like this in code now, so you end up with an error such as: `_axios.default.create is not a function`. The project is also not calling `vue-cli-service test` but the `jest` command directly, so variables from relevant `.env` files are not being installed because the mode is not set to `test` – but with that you could hack something akin to:

```
# .env.test.local
MOCK_API_PORT=9000 # for mock api server
VUE_APP_API_BASE_URL=http://localhost:${MOCK_API_PORT}
```

And remove `test/unit/__mocks__/axios.js`. T'is a bit nasty though.

Therefore, what would be a "best practice" solution to this?

If I remove `test/unit/__mocks__/axios.js` and replace with the following, then this is working for me currently both in testing and development, as well as for production builds:

```js
// src/utils/http.js

// For production builds, require a VUE_APP_API_BASE_URL environment variable to
// be set -- this will result in `baseURL` being statically embedded in the
// build instead of being derived at runtime.
//
// By default in development and test, requests are filtered through the mock
// API in `tests/mock-api`. To test directly against a local/live API instead,
// run development and test commands with the API_BASE_URL environment variable
// set. (See also: `devServer` setting in `vue.config.js`.)

import axios from 'axios';

const axiosInstance = axios.create({
  baseURL:
    process.env.VUE_APP_API_BASE_URL ||
    process.env.API_BASE_URL ||
    `http://localhost:${process.env.MOCK_API_PORT}`,
});

export default axiosInstance;
```

```diff
--- a/tests/unit/setup.js
+++ b/tests/unit/setup.js
-import axios from 'axios';
+import http from '@utils/http';

-  axios.defaults.headers.common.Authorization = options.currentUser
+  http.defaults.headers.common.Authorization = options.currentUser
```

This still feels a bit icky, though. Hence I'm wondering if I'm missing something obvious/slicker.

### PR DESCRIPTION
**Pull request by chrisvfritz**
@alexdilley Does this resolve the issues you noticed? What are your thoughts?

### CODE REVIEW

**Comment by alexdilley** [comment]
The `VUE_APP_API_BASE_URL` env var is only really a optimisation for production builds. It generates a bundle with the value of the variable statically embedded. So something like the following:

```js
create({baseURL:"https://api.example.com"})
```

as opposed to a more verbose lookup against the environment:

```js
create({baseURL:Object({
  NODE_ENV:"production",
  BASE_URL:"https://api.example.com",
  ...
}).API_BASE_URL})
```

I wasn't anticipating a refactor to use this over the equivalent without the `VUE_APP_` prefix, _except_ possibly a mention in the docs that this is favourable in certain circumstances for production builds (albeit a reiteration of what's in the vue-cli docs).

I think my issue relates to the way the axios node module as a whole was being mocked for Jest tests when presumably for most projects a module in app code will configure axios with things such as a base URL for each environment (based on environment variables). I couldn't see an entry point in the project currently where this can be configured without such an extension (e.g. how would builds for production have the prod API URL embedded). In my case, I've created `src/utils/http.js` which exports my axios instance. Perhaps this is needed alongside a `src/utils/__mocks__/http.js` counterpart. However, I'm finding that the `testURL` setting in `jest.config.js` is actually the thing that's directing requests and that `tests/units/__mocks__/axios.js` is redundant???

I hope I'm making _some_ sense 😕 I'll spend some time looking more into this.

The move from calling `jest` directly in scripts to calling via `vue-cli-service` does look like right since it'll utilise users' `.env` files (that's the 12-factor bit imo).

**Comment by alexdilley** [comment]
Just looked at the difference between builds using `.env` files for per-environment configuration. I'm mistaken: it is the case that _only_ vars prefixed with `VUE_APP_` are available in client-side code. I think I misread the built code previously: it's not the above, but the following:

```js
create({baseURL:Object({
  NODE_ENV:"production",
  BASE_URL:"/"
}).API_BASE_URL})
```

d'oh! (`NODE_ENV` and `BASE_URL` being the special variables exposed by vue-cli.)

So what you're doing in this PR probably does make sense. But let me come back to you after some further investigation.

I'm still curious as to what your recommendation might be for axios setup in production...is it the "module in `src/utils`" idea?

**Comment by chrisvfritz** [comment]
> I'm still curious as to what your recommendation might be for axios setup in production...is it the "module in `src/utils`" idea?

I just added a [couple comments](https://github.com/chrisvfritz/vue-enterprise-boilerplate/issues/25#issuecomment-378349976) to the issue which may answer that question. The tldr: when the API is always on the same domain (including subdomain) as the frontend, then no special hacks are necessary in production environments.

Let me know if that makes sense. 🙂 

And actually, now I'm second-guessing my rename of `API_BASE_URL` to `VUE_APP_API_BASE_URL`. I did that so that it could be available on the frontend, but I think actually accessing it in the frontend source would actually be an anti-pattern. Do you see something I might be missing or should I change it back?

**Comment by alexdilley** [comment]
As discussed on #25, I don't think the refactor to use a `VUE_APP_` prefix is necessary unless the context is production (where a configured `baseURL` would need to be embedded into client-side code). The rest LGTM 👍

**Comment by chrisvfritz** [comment]
Thanks! You were quite right that the axios mock was made unnecessary by providing a `testUrl`, so I've removed that as well. 🙂 Even simpler!

**Pull request merged**
